services:
  frontend:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173

  backend:
    build:
      context: .
      dockerfile: apps/wrapper/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env