services:
  frontend:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/wrapper
      dockerfile: Dockerfile
    ports:
      - "3000:3000"