services:
  frontend:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: apps/wrapper/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./.env